name: mint_web
description: Mint doctor web-portal
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cloud_firestore: 4.9.0
  collection: ^1.17.1
  data_table_2: ^2.5.7
  emoji_picker_flutter: ^1.6.1
  firebase_auth: 4.8.0
  firebase_core: 2.15.1
  firebase_storage: 11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.11.7
  flutter_portal: ^1.1.4
  flutter_sound: ^9.2.13
  flutter_svg: ^2.0.7
  freezed_annotation: 2.2.0
  get_it: ^7.6.4
  http: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  meta: ^1.9.1
  mint_core:
    path: '../../packages/mint_core'
  reactive_forms: ^16.1.0
  reactive_forms_annotations: ^4.0.0
  rxdart: ^0.27.7
  sliver_tools: ^0.2.12
  syncfusion_flutter_calendar: ^23.1.36
  universal_html: ^2.2.4

dev_dependencies:
  auto_route_generator: ^7.3.0
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  reactive_forms_generator: ^4.0.0
  very_good_analysis: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      class_name: MintFontFamily
  colors:
    outputs:
      class_name: MintColors
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/SFProDisplay-Medium.otf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/noto_color_emoji/NotoColorEmoji-Regular.ttf
          weight: 400
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
